### ISSUE TITLE
Exception lỗi dữ liệu trong việc nhập của các chức năng

### ISSUE THREAD

**Issue by tieminhthanh** [CongLuanTran/BookRental#5]
Khi nhập dữ liệu sai ở các chức năng 2 3 4 5 thì nó bị lỗi đá văng ra chướng trình
Như kiêu nhập giá tiền nhập ký tự thì bị lỗi Exception

![Screenshot 2024-03-19 233848](https://github.com/CongLuanTran/BookRental/assets/159162920/57656a07-7b33-473c-8b04-d02950e2485f)

**Comment by CongLuanTran** [comment]
done
